services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_GATEWAY_TASKS_URL: http://localhost:3001
      REACT_APP_API_GATEWAY_AUTHENTICATION_URL: http://localhost:3001

  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      TOKEN_SECRET: mytokensecret
      TASKS_API_URL: http://tasks_server:5000
    depends_on:
      - tasks_server

  tasks_server:
    build:
      context: ./tasks_server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_TEST_URI: mongodb://mongodb:27017/testdb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

networks:
  default:
    name: my-network
